name: Windows Build

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest  # 使用 Windows 环境

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install SFML (Windows)
      run: |
        # 这里可以下载 SFML 并设置环境变量
        # 例如：choco install sfml（如果 SFML 在 Chocolatey 里）

    - name: Build with MSBuild
      run: |
        # 使用 Visual Studio 自带的 MSBuild 编译 .sln
        msbuild AmandsController.sln /p:Configuration=Release
