name: CMake Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # 确保拉取完整代码

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++ libsfml-dev

    - name: Configure CMake
      run: cmake -B build -S .
      working-directory: ${{ github.workspace }}  # 关键修复：强制使用根目录

    - name: Build
      run: cmake --build build

    - name: Run executable (optional)
      run: ./build/AmandsController  # 如果生成可执行文件
