name: Windows Build

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install SFML
      run: |
        curl -L -o sfml.zip https://www.sfml-dev.org/files/SFML-2.5.1-windows-vc17-64-bit.zip
        mkdir sfml
        tar -xf sfml.zip -C sfml --strip-components=1
        echo "SFML_DIR=$PWD/sfml" >> $GITHUB_ENV

    - name: Configure CMake
      run: |
        cmake -B build -S . -DSFML_DIR=${{ env.SFML_DIR }}

    - name: Build
      run: |
        cmake --build build --config Release
