name: CMake Build

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest  # 或 ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies (Windows)
      if: runner.os == 'Windows'
      run: |
        choco install sfml -y  # 使用 Chocolatey 安装 SFML
        choco install cmake -y

    - name: Install dependencies (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake libsfml-dev g++

    - name: Build
      run: |
        cmake -B build -S .
        cmake --build build
