name: CMake Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++ libsfml-dev

    - name: Configure CMake
      run: cmake -B build -S .  # 关键修复：显式指定源码和构建目录

    - name: Build
      run: cmake --build build

    - name: Run executable (optional)
      run: ./build/AmandsController  # 如果生成可执行文件
