name: Windows Build

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest  # 使用 Windows 环境

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Find MSBuild path
      id: msbuild
      uses: microsoft/setup-msbuild@v1  # 专门用于设置 msbuild 的 GitHub Action

    - name: Build with MSBuild
      run: |
        # 确保 .sln 文件存在（如果不在根目录，替换为正确路径）
        ls *.sln
        # 使用 msbuild 编译
        msbuild AmandsController.sln /p:Configuration=Release
